conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:listing_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

recruit-me/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('listings/', include('listing.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'w-full py-4 px-6 rounded-xl border',
        'placeholder': 'Change username',
    }))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
        'class': 'w-full py-4 px-6 rounded-xl border',
        'placeholder': 'Change email',
    }))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'w-full py-4 px-6 rounded-xl border', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

core/views.py
from django.shortcuts import render, redirect
from listing.models import Category, Listing
from django.contrib import messages

from .forms import SignupForm, UpdateUserForm, UpdateProfileForm
from django.contrib.auth.decorators import login_required



def index(request):
    listings = Listing.objects.filter(is_full=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'listings': listings,
    })




def contact(request):
    return render(request, 'core/contact.html')




def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('core:profile')

    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user)

    return render(request, 'core/profile.html', {'user_form': user_form, 'profile_form': profile_form})

core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="py-5 px-8 flex justify-between items-center border-b border-gray-200">
            
            <a href="/" class="px-6 py-3 text-4xl font-semibold rounded-xl unique-title hover:text-black-500">RecruitMe</a>
            <style>
                .unique-title:hover {
                    background-color: #008fb3;
                }
                
            </style>
            <div class="space-x-6">
                <a href="{% url 'listing:new' %}" class="px-6 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">New Project Listing</a>
                <a href="{% url 'listing:listings' %}" class="px-6 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Browse</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Dashboard</a>
                    <a href="{% url 'core:profile' %}" class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">My Profile</a>
                    <a href="{% url 'core:logout' %}" class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Logout</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>


        <footer class="py-6 px-6 flex justify-between bg-gray-800" style="background-color: #e6faff;">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400 text-2xl">About</h3>

                <p class="text-lg text-gray-500">Built with <strong>Django</strong> and <strong>Python</strong></p>
                <p class="text-lg text-gray-500">Integrated with <strong>PostgresSQL</strong> on <strong>Amazon AWS RDS</strong></p>
                <p class="text-lg text-gray-500">Deployed on <strong>AWS Elastic Beanstalk</strong></p>
                <br>
                <p class="text-lg text-gray-500">If you like this project, please reach out at [<strong>surven02@gmail.com</strong>]!</p>
                <p class="text-lg text-gray-500">Or visit my Github at <a href="https://github.com/surven02"><strong>https://github.com/surven02</strong></a></p>

            </div>

            
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}


{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold">Newest Project Listings</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for listing in listings %}
                <div>
                    <a href="{% url 'listing:detail' listing.id %}">
                        <div>
                            <img src="{{ listing.listing_logo.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ listing.project_name }}</h2>
                            <p class="text-gray-500"><strong>Category:</strong> {{ listing.category }}</p>
                            <p class="text-gray-500"><strong>Skills needed:</strong> {{ listing.skills_needed }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold">Project Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Log In</button>
    </form>
</div>
{% endblock %}

core/templates/core/profile.html
{% extends "core/base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="small mb-1">Username:</label>
                            {{ user_form.username }}
                        <label class="small mb-1">Email:</label>
                            {{ user_form.email }}
                    </div>
                    <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Save Changes</button>
            <button type="reset" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Reset</button>
        </form>
    </div>
{% endblock content %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="px-4 py-3 text-lg font-semibold rounded-xl unique-title hover:bg-teal-700">Submit</button>
    </form>
</div>
{% endblock %}